SPARQL

prefix crime: <http://linked.opendata.cz/ontology/crime#>
prefix dct: <http://purl.org/dc/terms/>

WITH <http://linked.opendata.cz/resource/domain/crimestatistics/dataset>
DELETE { ?trestnyCin_prev crime:validTo ?validTo_prev . ?trestnyCin_prev crime:nextVersion ?trestnyCin_prev_next . ?trestnyCin_prev_next crime:previousVersion ?trestnyCin_prev . }
INSERT { ?trestnyCin_prev crime:validTo ?validFrom . ?trestnyCin_prev crime:nextVersion ?trestnyCin . ?trestnyCin crime:validTo ?validTo_prev . ?trestnyCin crime:previousVersion ?trestnyCin_prev  . ?trestnyCin crime:nextVersion ?trestnyCin_prev_next . ?trestnyCin_prev_next crime:previousVersion ?trestnyCin . }
where
{
    ?trestnyCin a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
      crime:validFrom ?validFrom ;
      dct:isVersionOf ?trestnyCin_master .
    FILTER(NOT EXISTS { ?trestnyCin crime:validTo ?validTo . }) .

    ?trestnyCin_prev a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
        crime:validFrom ?validFrom_prev ;
        crime:validTo ?validTo_prev ;
        dct:isVersionOf ?trestnyCin_prev_master .

    FILTER(?trestnyCin_master = ?trestnyCin_prev_master && ?validFrom_prev < ?validFrom && ?validFrom < ?validTo_prev) .

    OPTIONAL {?trestnyCin_prev crime:nextVersion ?trestnyCin_prev_next . } .
};

SPARQL

prefix crime: <http://linked.opendata.cz/ontology/crime#>
prefix dct: <http://purl.org/dc/terms/>

WITH <http://linked.opendata.cz/resource/domain/crimestatistics/dataset>
INSERT { ?trestnyCin crime:validTo ?validFrom_oldest . ?trestnyCin crime:nextVersion ?trestnyCin_oldest . ?trestnyCin_oldest crime:previousVersion ?trestnyCin . }
where
{
    ?trestnyCin a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
      crime:validFrom ?validFrom ;
      dct:isVersionOf ?trestnyCin_master .
    FILTER(NOT EXISTS { ?trestnyCin crime:validTo ?validTo . }) .

    ?trestnyCin_oldest a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
        crime:validFrom ?validFrom_oldest ;
        dct:isVersionOf ?trestnyCin_oldest_master .

    FILTER(?trestnyCin_master = ?trestnyCin_oldest_master && ?validFrom < ?validFrom_oldest && NOT EXISTS{ ?trestnyCin_oldest crime:previousVersion ?trestnyCin_oldest_prev . } ) .
};

SPARQL

prefix crime: <http://linked.opendata.cz/ontology/crime#>
prefix dct: <http://purl.org/dc/terms/>

WITH <http://linked.opendata.cz/resource/domain/crimestatistics/dataset>
INSERT { ?trestnyCin crime:validTo "9999-12-31 23:59:59"^^xsd:dateTime . }
where
{
    ?trestnyCin a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
      dct:isVersionOf ?trestnyCin_prev_master .
    FILTER(NOT EXISTS { ?trestnyCin crime:validTo ?validTo . }) .
};

SPARQL

prefix crime: <http://linked.opendata.cz/ontology/crime#>
prefix dct: <http://purl.org/dc/terms/>

WITH <http://linked.opendata.cz/resource/domain/crimestatistics/dataset>
INSERT { ?trestnyCin_orig a <http://linked.opendata.cz/ontology/crime#TrestnyCin> . ?trestnyCin_orig dct:hasVersion ?trestnyCin . }
where
{
    ?trestnyCin a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
        dct:isVersionOf ?trestnyCin_orig .
};