SPARQL

prefix crime: <http://linked.opendata.cz/ontology/crime#>
prefix dct: <http://purl.org/dc/terms/>

WITH <http://linked.opendata.cz/resource/domain/crimestatistics/dataset>
INSERT { ?trestnyCin crime:validTo ?validFrom_oldest . ?trestnyCin crime:nextVersion ?trestnyCin_oldest . ?trestnyCin_oldest crime:previousVersion ?trestnyCin . }
where
{
    ?trestnyCin a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
      crime:validFrom ?validFrom ;
      dct:isVersionOf ?trestnyCin_master .
    FILTER(NOT EXISTS { ?trestnyCin crime:validTo ?validTo . }) .

    ?trestnyCin_oldest a <http://linked.opendata.cz/ontology/crime#TrestnyCin> ;
        crime:validFrom ?validFrom_oldest ;
        dct:isVersionOf ?trestnyCin_oldest_master .

    FILTER(?trestnyCin_master = ?trestnyCin_oldest_master && ?validFrom < ?validFrom_oldest && NOT EXISTS{ ?trestnyCin_oldest crime:previousVersion ?trestnyCin_oldest_prev . } ) .
};